# Generated by Django 5.0.3 on 2024-03-16 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=25)),
                ('contact', models.IntegerField()),
                ('address', models.TextField(max_length=50)),
                ('specification', models.CharField(max_length=30)),
                ('qualification', models.CharField(max_length=20)),
                ('available_date', models.DateField()),
                ('checkin_time', models.TimeField()),
                ('checkout_time', models.TimeField(blank=True, null=True)),
            ],
        ),
    ]
