# Generated by Django 5.0.3 on 2024-03-17 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_doctordetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctordetail',
            old_name='doctor_name',
            new_name='doctor_id',
        ),
    ]
