# Generated by Django 5.0.3 on 2024-03-21 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_rename_doctor_name_doctordetail_doctor_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorAvailableDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_day', models.CharField(max_length=50)),
                ('availabletime_slot', models.BinaryField(verbose_name=models.TimeField())),
                ('doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor')),
            ],
        ),
    ]
